A recommender system with the given data using User Based Collaborative Filtering.  
This dataset is related to the video gaming industry and a survey was conducted to build a   
recommendation engine so that the store can improve the sales of its gaming DVDs.   
Following is a Recommendation Engine that suggests top selling DVDs based on which DVD the customer buys.

In [670]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [671]:
sns.set()

In [672]:
# import Dataset 
games = pd.read_csv("game.csv", encoding = 'utf8')

In [673]:
games.shape

(5000, 3)

In [674]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   userId  5000 non-null   int64
 1   game    5000 non-null   object
 2   rating  5000 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 117.3+ KB

In [675]:
games.sample(7)

      userId                                    game  rating
1343    3633  Tom Clancy's Splinter Cell: Conviction     5.0
4580     401                   NCAA March Madness 06     5.0
2780    1322   The Lord of the Rings: The Two Towers     2.5
1017    2748      Company of Heroes: Opposing Fronts     4.0
2768    1270                MotorStorm: Pacific Rift     5.0
4441    2003                     Donkey Kong Country     3.0
2038    5546                                Gunpoint     4.5

In [676]:
games['rating'].unique()

array([4. , 5. , 4.5, 3. , 1. , 3.5, 1.5, 2. , 2.5, 0.5])

In [677]:
gamemat = games.pivot_table(index='userId',columns='game',values='rating')
gamemat1= gamemat.fillna(0)
gamemat1.head()

game,'Splosion Man,007: The World is Not Enough,10 Second Ninja X,1001 Spikes,1701 A.D.,1979 Revolution: Black Friday,2002 FIFA World Cup,2010 FIFA World Cup South Africa,3D After Burner II,3D Gunstar Heroes,...,echochrome,echochrome ii,escapeVektor: Chapter 1,flower,ilomilo,inFamous,inFamous 2,inFamous: Festival of Blood,inFamous: Second Son,page not found
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [678]:
gamemat1.shape

(3261, 3438)

In [679]:
#create similarity matrix for users
from sklearn.metrics.pairwise import cosine_similarity
user_similarity_matrix = cosine_similarity(gamemat1)

In [680]:
user_similarity_matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

This is the matrix based on which we will recommmend games to users

In [681]:
user_similarity_matrix.shape

(3261, 3261)

In [682]:
gamemat1.tail()

game,'Splosion Man,007: The World is Not Enough,10 Second Ninja X,1001 Spikes,1701 A.D.,1979 Revolution: Black Friday,2002 FIFA World Cup,2010 FIFA World Cup South Africa,3D After Burner II,3D Gunstar Heroes,...,echochrome,echochrome ii,escapeVektor: Chapter 1,flower,ilomilo,inFamous,inFamous 2,inFamous: Festival of Blood,inFamous: Second Son,page not found
userId,,,,,,,,,,,,,,,,,,,,,
7110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7116,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7117,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7120,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [683]:
#coonvert to datframe for ease of usage
user_similarity_df= pd.DataFrame(user_similarity_matrix,index=gamemat1.index,columns=gamemat1.index)

In [684]:
user_similarity_df

userId,1,2,3,5,6,7,8,10,11,12,...,7101,7102,7104,7107,7108,7110,7116,7117,7119,7120
userId,,,,,,,,,,,,,,,,,,,,,
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
7116,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7117,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7120,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [685]:
#get similar users where cosine_similarity > 0 
def get_similar_users(userId):
    idx = []
    if userId in user_similarity_df.index:
        similar_users = user_similarity_df[user_similarity_df[userId]>0][userId]
        similar_users = similar_users.index.drop(userId).sort_values(ascending=False)
    else:
        similar_users=np.array([])

    similar_users
    if similar_users.shape[0] :
        return similar_users.values
    else:
        return []

In [686]:
#get games where similar users have rated more than 3
def get_recommended_games(users):
    return games[(games['userId'].isin(users)) & (games['rating']>3)]['game'].unique()

In [687]:
#get recommendations for user 2
get_recommended_games(get_similar_users(2))

array(['Battlefield 1942: The Road to Rome',
       'Atelier Rorona Plus: The Alchemist of Arland'], dtype=object)

In [688]:
#get recommendations for user 6
get_recommended_games(get_similar_users(6))

array(["Tony Hawk's Pro Skater 2", 'Command & Conquer 3: Tiberium Wars',
       'World of Tanks'], dtype=object)